### ISSUE TITLE
JSP Files

### ISSUE THREAD

**Issue by UniWrighte** [wakatime/wakatime#185] opened 2019-06-25 20:26 UTC
Files ending with .jsp should register as Java development.

**Comment by alanhamlett** [comment] 2019-06-26 02:14
Duplicate of wakatime/wakatime#185

**Closed by alanhamlett** 2019-06-26 02:14 UTC
Labels: question

**Comment by alanhamlett** [comment] 2019-06-26 02:16
Fixed with a global rule matching `.jsp` extensions. Thanks for improving language detection!
