### ISSUE TITLE
wakatime not work using ssh

### ISSUE THREAD

**Issue by stevenyvette** [wakatime/wakatime#135] opened 2018-04-27 02:49 UTC
Hi, 
I installed wakatime using the method of   [Terminal/bash](https://wakatime.com/terminal) on my remote server.
When I ssh to the remote server in XShell, it seems wakatime doesn't record my activity.
So, any solution or it just doesn't work through ssh ?~

**Comment by alanhamlett** [comment] 2018-04-27 05:16
WakaTime only works in the shell on your local machine, unless you also install WakaTime on your remote machine.

**Comment by stevenyvette** [comment] 2018-04-27 07:43
@alanhamlett 

Yes，I do install wakatime on my remote server.
When I ssh and code, it just doesn't record anything   :(
So, I wonder if the problem is on ssh.
Or shall I also install WakaTime on my local **windows** machine?

**Comment by alanhamlett** [comment] 2018-06-13 16:13
Duplicate of #72.

**Closed by alanhamlett** 2018-06-13 16:13 UTC
