### ISSUE TITLE
does not heartbeat "external files"

### ISSUE THREAD

**Issue by HMAZonderland** [wakatime/wakatime#144] opened 2018-07-11 10:27 UTC
When I edit an external file through SFTP (for example) the heartbeat is ignored. My IDE is PhpStorm 2018.1.6.

Is there a way to have it heartbeat files such as these? Or do I have to pull an entire project locally to make sure Wakatime can do its magic on it?

```json
{"now": "2018/07/11 12:23:49 +0200", "version": "10.2.1", "plugin": "PhpStorm/2018.1.6 PhpStorm-wakatime/9.2.0", "time": 1531304620.148, "caller": "/Users/Hugo/.wakatime/wakatime-master/wakatime/main.py", "lineno": 51, "is_write": true, "file": "<8c2eac0a-fe87-4026-b694-c017e7fd07c6>/backend/tpl/dashboard.tpl", "level": "DEBUG", "message": "File does not exist; ignoring this heartbeat."}
```

**Comment by alanhamlett** [comment] 2018-07-12 16:02
WakaTime doesn't yet support reading remote files. I'm not sure if it's as simple as trying to read the file instead of checking if it exists first, but would be nice to add remote file support since it's a dependency for fixing wakatime/wakatime-mode#27.

**Comment by alanhamlett** [comment] 2018-07-12 16:05
Closing as duplicate of #72.

**Closed by alanhamlett** 2018-07-12 16:05 UTC
