### ISSUE TITLE
VIM slows down when Wakeatime is active

### ISSUE THREAD

**Issue by c10b10** [wakatime/wakatime#39] opened 2015-12-18 09:46 UTC
I'm on OSX 10.11.2 with Vim 7.4 (85), and sadly, while I have the plugin installed, everything lags slightly.

The only fix I could find is disabling the plugin.

**Comment by alanhamlett** [comment] 2015-12-19 17:12
Are you using gVim or Vim inside Terminal? I'm using Vim in iTerm2 on OSX 10.11.2 but don't notice any lagging.

Can you run `htop -d 10` and filter to only your user's processes (http://www.thegeekstuff.com/2011/09/linux-htop-examples/) and see what's happening? The plugin checks a global variable every keystroke to see if enough time has passed to send another heartbeat and maybe that's causing lag.

**Comment by alanhamlett** [comment] 2015-12-25 07:17
Closing this issue as duplicate of wakatime/vim-wakatime#35.

**Closed by alanhamlett** 2015-12-25 07:17 UTC
